/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.17
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using OpenApi.Pets.Sdk.Client;
using OpenApi.Pets.Sdk.Api;
// uncomment below to import models
//using OpenApi.Pets.Sdk.Model;

namespace OpenApi.Pets.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing StoreApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StoreApiTests : IDisposable
    {
        private StoreApi instance;

        public StoreApiTests()
        {
            instance = new StoreApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StoreApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StoreApi
            //Assert.IsType<StoreApi>(instance);
        }

        /// <summary>
        /// Test DeleteOrder
        /// </summary>
        [Fact]
        public void DeleteOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long orderId = null;
            //instance.DeleteOrder(orderId);
        }

        /// <summary>
        /// Test GetInventory
        /// </summary>
        [Fact]
        public void GetInventoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetInventory();
            //Assert.IsType<Dictionary<string, int>>(response);
        }

        /// <summary>
        /// Test GetOrderById
        /// </summary>
        [Fact]
        public void GetOrderByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long orderId = null;
            //var response = instance.GetOrderById(orderId);
            //Assert.IsType<Order>(response);
        }

        /// <summary>
        /// Test PlaceOrder
        /// </summary>
        [Fact]
        public void PlaceOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Order? order = null;
            //var response = instance.PlaceOrder(order);
            //Assert.IsType<Order>(response);
        }
    }
}
